/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "pin_led_aliases.h"
#include "pin_led.h"
#include "random.h"
#include "isr_timer.h"
#include "clk_timer.h"
#include "pin_snd_aliases.h"
#include "pin_snd.h"
#include "HORIZ.h"
#include "VGA_aliases.h"
#include "VGA.h"
#include "VERT.h"
#include "VSYNC.h"
#include "HSYNC.h"
#include "DMA_dma.h"
#include "PIXEL.h"
#include "NEWLINE.h"
#include "HSYNC_OUT_aliases.h"
#include "HSYNC_OUT.h"
#include "VSYNC_OUT_aliases.h"
#include "VSYNC_OUT.h"
#include "VGA_CLK.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

