/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "pin_led_aliases.h"
#include "pin_led.h"
#include "random.h"
#include "isr_timer.h"
#include "clk_timer.h"
#include "pin_snd_aliases.h"
#include "pin_snd.h"
#include "HORIZ.h"
#include "VGA_aliases.h"
#include "VGA.h"
#include "VERT.h"
#include "VSYNC.h"
#include "HSYNC.h"
#include "DMA_dma.h"
#include "PIXEL.h"
#include "NEWLINE.h"
#include "HSYNC_OUT_aliases.h"
#include "HSYNC_OUT.h"
#include "VSYNC_OUT_aliases.h"
#include "VSYNC_OUT.h"
#include "VGA_CLK.h"
#include "Row_1_aliases.h"
#include "Row_1.h"
#include "Row_4_aliases.h"
#include "Row_4.h"
#include "Row_2_aliases.h"
#include "Row_2.h"
#include "Row_3_aliases.h"
#include "Row_3.h"
#include "Col_1_aliases.h"
#include "Col_1.h"
#include "Col_2_aliases.h"
#include "Col_2.h"
#include "Col_3_aliases.h"
#include "Col_3.h"
#include "Col_4_aliases.h"
#include "Col_4.h"
#include "pin_oled_mosi_aliases.h"
#include "pin_oled_mosi.h"
#include "pin_oled_clk_aliases.h"
#include "pin_oled_clk.h"
#include "pin_oled_cs_aliases.h"
#include "pin_oled_cs.h"
#include "pin_oled_dc_aliases.h"
#include "pin_oled_dc.h"
#include "pin_oled_rst_aliases.h"
#include "pin_oled_rst.h"
#include "spi_oled.h"
#include "spi_oled_PVT.h"
#include "pin_test_aliases.h"
#include "pin_test.h"
#include "isr_oled.h"
#include "spi_oled_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

